### ISSUE TITLE
Error while embedding

### ISSUE THREAD

**Issue by Zack-Bloodshot** [iiPythonx/lrcup#4]
While using the "embed" command, encountered this error:

`Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/lrcup", line 8, in <module>                                                   sys.exit(lrcup())                                                   ^^^^^^^                                         File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__               return self.main(*args, **kwargs)                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)                                           ^^^^^^^^^^^^^^^^                                    File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke                 return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke                 return ctx.invoke(self.callback, **ctx.params)                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke                  return __callback(*args, **kwargs)                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^                       File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/lrcup/__main__.py", line 126, in embed               AudioFile(destination).set_lyrics("synced" if "[" in lyrics else "unsynced", lyrics)                                  ^^^^^^^^^^^^^^^^^^^^^^                                   File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/lrcup/audio/__init__.py", line 33, in __init__       if path.suffix not in CLASS_MAPPING:                          ^^^^^^^^^^^                                         AttributeError: 'str' object has no attribute 'suffix'`

I think the *path* variable in the *embed* function call in the *\_\_main\_\_.py* file is a string, while the input parameter for the initialise function for the audiohandling class is  an object.

**Comment by iiPythonx** [comment]
Fixed in 0.5.4 (c28616fddc797667d4a626e9878dd8e8a4c531ca) after upgrading your problem should be resolved.
